name: CI/CD actions [Linux]
on:
  push:
    branches: [master, develop]
    tags:
      - 'v*'
    paths-ignore:
      - docs/**
      - README.md
      - CHANGELOG.md
  pull_request:
    branches: [master, develop]
    paths-ignore:
      - docs/**
      - README.md
      - CHANGELOG.md
env:
  CONAN_VERSION: 1.53.0
jobs:
  cpplint:
    runs-on: ubuntu-20.04
    name: Check C++ format and style
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip3 install -r python/requirements/format.txt
      - name: Run cpplint
        run: find {benchmarks,tests,sources,wavelet_buffer,examples,python/src}/ -name "*.cc" -o -name "*.h" | xargs cpplint
      - name: Run clang-format
        run: find {benchmarks,tests,sources,wavelet_buffer,examples,python/src}/ -name "*.cc" -o -name "*.h" | xargs clang-format --dry-run --Werror
  build_test:
    needs: [cpplint]
    runs-on: ${{ matrix.os }}
    name: Build and test C++ part
    strategy:
      matrix:
        build_type: [Debug, Release]
        os: [ubuntu-20.04, windows-2019, macos-12]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          pipx install conan==${{ env.CONAN_VERSION }}
      - name: Build tests, benchmarks and examples
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DWB_BUILD_TESTS=ON -DWB_BUILD_BENCHMARKS=ON -DWB_BUILD_EXAMPLES=ON -DCODE_COVERAGE=ON ..
          cmake --build . -j --config ${{ matrix.build_type }}
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
